title: Research Homepage
email: mj9vc@mst.edu
description: >-
  PhD Candidate (Computer Science) â€” Multimodal AI, Computer Vision, Data Fusion, LVLMs.
baseurl: "" # keep empty for USERNAME.github.io
url: "https://mizanJewel.github.io"     # set to https://USERNAME.github.io when ready
markdown: kramdown
permalink: pretty
